/**
 * Created by consultadd on 9/7/17.
 */

const dummydata=[

    { id: 0,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]},
            {cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}, ] },

    { id: 1,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 2,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 3,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 4,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 5,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 6,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 7,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 8,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 9,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated LoremIpsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

        { id: 10,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

        { id: 11,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },


    { id: 12,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]},
            {cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}, ] },

    { id: 13,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 14,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 15,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 16,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 17,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 18,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 19,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 20,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 21,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated LoremIpsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 22,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 23,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },
    { id: 24,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 25,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 26,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 27,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 28,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 29,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 30,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 31,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 32,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated LoremIpsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 33,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

    { id: 34,title:'What is Lorem Ipsum?',preview:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.', time: 'jun 21, 2017',slug:'Lorem-Ipsum-has-been-the-industry', content:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        comments:[{cmt:'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..', nested:[{ncmtliked:false,ncmt:'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. '},{ncmtliked:false,ncmt:'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'}]}] },

];

export default dummydata;